---
- name: Dockhost_Example
  hosts: all
  vars: 
    users:
      - username: "nglase2s"
        groups: "sudo"
      - username: "kbeppe2s"
        groups: "sudo"
      - username: "nresch2s"
        groups: "sudo"
  tasks:
  - name: Hello World
    debug:
      msg: "Hello World"

  - name: Install htop
    become: yes
    apt:
      pkg: htop
      state: latest
      update_cache: yes
  - name:    Add Docker GPG key
    become: yes
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name:    Add Docker APT repository
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  - name:    Install Docker
    become: yes
    apt:     name=docker-ce
  - name: add ssh keys
    authorized_key:
      user: "vagrant"
      key: "{{ lookup('file', '../../ansible/pub_keys/' + item.username + '.key.pub') }}"
    with_items: "{{ users }}"
